# Load Antigen
source ~/antigen.zsh

# Load oh-my-zsh defaults
antigen use oh-my-zsh

# Load plugins
antigen bundle pyenv

antigen bundle command-not-found
antigen bundle colored-man-pages
antigen bundle fzf
antigen bundle pip
antigen bundle sudo
antigen bundle rtakasuke/zsh-duration --branch=main
antigen bundle zsh-interactive-cd
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

# Set theme
antigen theme robbyrussell

# Finish Antigen
antigen apply

# Export preferred editor if installed
which nvim &>/dev/null
if [[ $? == 0 ]]; then
  export EDITOR='nvim'
fi
