---
- name: Clone homelab repo # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/sakibc/homelab.git
    dest: "{{ ansible_env.HOME }}/homelab"
    version: main

- name: Recompose
  become: true
  ansible.builtin.shell: docker compose down && docker compose up -d
  args:
    chdir: "{{ ansible_env.HOME }}/homelab"
