---
- name: Learn about hosts
  hosts: all

- name: Set up home lab main server
  hosts: main_server
  roles:
    - role: control_node
      tags:
        - control_node
    - role: main_server
      tags:
        - main_server

- name: Set up Pihole
  hosts: pihole
  roles:
    - pihole
  tags:
    - pihole
