---
- name: Learn about hosts
  hosts: all

- name: Set up home lab main server
  hosts: main_server
  roles:
    - main_server
    - control_node

- name: Set up Pihole
  hosts: pihole
  roles:
    - pihole
